version: '3.1'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo

  adminer:
    command: php -S 0.0.0.0:8080 -t /var/www/html
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - ADMINER_DESIGN=pepa-linha
      - ADMINER_DEFAULT_DB_USER=demo
      - ADMINER_DEFAULT_DB_PASSWORD=demo
      - ADMINER_DEFAULT_DB_DRIVER=PgSQL
      - ADMINER_DEFAULT_DB_NAME=demo
